{
  config,
  pkgs,
  lib,
  ...
}:

{
 users.users.corvidae = {
   isNormalUser = true;
   description = "corvidae";
   extraGroups = [ "networkmanager" "wheel" "libvirtd" ];
   shell = pkgs.bash;
   packages = with pkgs; [
     asciinema
     ansible
     appimage-run
     bat
     brave
     btop
     cockatrice
     discord
     dnsutils
     doggo
     du-dust
     duf
     element-desktop
     fastfetch
     fd
     ffmpeg-full
     firefox
     fzf
     ghostty
     gimp
     gnucash
     gnupg
     grim
     handbrake
     html-tidy
     joplin-desktop
     keepassxc
     lazygit
     libreoffice
     librewolf
     lsd
     lshw
     mpv
     nfs-utils
     nftables
     nushell
     obs-studio
     obs-studio-plugins.obs-backgroundremoval
     openssl
     p7zip
     pandoc
     pavucontrol
     pciutils
     pinentry-all
     pipewire
     podman-compose
     protonplus
     protonup-qt
     reco
     ripgrep
     ripgrep-all
     sd
     slurp
     starship
     texliveFull
     texmaker
     tldr
     unzip
     uv
     wf-recorder
     wget2
     wl-clipboard-rs
     wofi
     xdg-desktop-portal
     xdg-desktop-portal-gtk
     xdg-desktop-portal-wlr
     xh
     xwayland
     zeal
     zed-editor
     zellij
     zoxide
   ];
  };
}
