{
  config,
  pkgs,
  lib,
  ...
}:

{
 users.users.corvidae = {
   isNormalUser = true;
   description = "corvidae";
   extraGroups = [ "networkmanager" "wheel" "libvirtd" ];
   shell = pkgs.bash;
   packages = with pkgs; [
     asciinema
     ansible
     appimage-run
     bat
     brave
     btop
     cockatrice
     diff-so-fancy
     discord
     dnsutils
     doggo
     dust
     duf
     element-desktop
     fastfetch
     fd
     ffmpeg-full
     firefox
     fuzzel
     fzf
     ghostty
     gimp
     gnupg
     google-chrome
     grim
     handbrake
     html-tidy
     inkscape
     imagemagick
     joplin-desktop
     kdePackages.kdenlive
     keepassxc
     krita
     lazygit
     libreoffice
     librewolf
     lmms
     lsd
     lshw
     mako
     mpv
     musikcube
     nfs-utils
     nftables
     nushell
     obs-studio
     obs-studio-plugins.obs-backgroundremoval
     oklch-color-picker
     openssl
     p7zip
     pandoc
     pavucontrol
     pciutils
     pinentry-all
     pipewire
     podman-compose
     protonplus
     protonup-qt
     reco
     ripgrep
     ripgrep-all
     sd
     signal-desktop
     slurp
     starship
     texliveFull
     texmaker
     tldr
     unzip
     uv
     wf-recorder
     wget2
     wl-clipboard-rs
     xdg-desktop-portal
     xdg-desktop-portal-gnome
     xdg-desktop-portal-gtk
     xdg-desktop-portal-wlr
     xh
     xwayland
     yt-dlp
     zeal
     zed-editor
     zellij
     zsnes2
     zoxide
     zstd
   ];
  };
}
